### PR TITLE
Fix Buffer deprecation warning at startup

### LINKED ISSUE #147: DeprecationWarning: Buffer() is deprecated
[Error - 9:14:49 PM] (node:11440) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### PR DESCRIPTION
**Pull request by alisabzevari**
To fix #147,

This PR fixes Buffer deprecation warning which caused by `vscode-languageclient` dependency. After updating this dependency I had to update a few other packages as well. The updated packages had some breaking changes:

* Instantiating `TextDocuments` in language server has changed. A new package called `vscode-languageserver-textdocument` needed to fix it. See docs [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-server).
* The new packages needed newer version of node (v12), so I updated `@types/node`.
* `vscode` package has been deprecated and replaced by two separated packages: `@types/vscode` and `vscode-test`. See migration docs [here](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode).
* The new `vscode-test` provides a new testing mechanism. So, I have updated some configurtion scripts in `src/test` directory. Additionally, I had to install `mocha` and `glob` for that.

### CODE REVIEW

File: src/language/server.ts [hunk 1]
```diff
@@ -108,7 +109,7 @@ connection.onInitialize((_params) : InitializeResult => {
   shouldSendDiagnosticRelatedInformation = _params.capabilities && _params.capabilities.textDocument && _params.capabilities.textDocument.publishDiagnostics && _params.capabilities.textDocument.publishDiagnostics.relatedInformation;
   return {
     capabilities: {
-      textDocumentSync: documents.syncKind,
+      textDocumentSync: TextDocumentSyncKind.Full,
```
Comment (alisabzevari) [inline src/language/server.ts:112]: I am not sure whether `SyncKind` should be `Full` or `Incremental`.

Comment (Borvik) [reply src/language/server.ts:112]: I'm not sure either.  In my own test upgrades, I was using Incremental - but I didn't get very far in the testing, and upon 2nd thoughts - Full might be the better option here.

**Comment by Borvik** [comment]
This is a little weird - I had actually tested with the following package upgrades, which I believe were the latest at the time I tested:
```
"@types/node": "^12.12.0",
"@types/vscode": "^1.47.0",
"typescript": "^4.0.2",
"vscode-languageclient": "^6.1.3",
"vscode-languageserver": "^6.1.1",
"vscode-languageserver-textdocument": "^1.0.1",
```

I'll do some testing today so we can merge this.

First thoughts - the test files that are actually part of the project are just the default files included via the initial bootstrap creation of the extension, and since I never actually implemented any sort of testing - I would suggest just removing the test index and related dependencies.

**Review by Borvik — APPROVED** [review]
